import {StyleSheet} from 'react-vr';

export default styles = StyleSheet.create({
  rootView: {
    layoutOrigin: [0.5, 0.5],
    position: 'absolute',
  },
  triggerContainer: {
    transform: [{rotateY: 0}, {translateZ: -3}],
  },
  triggerButton: {
    borderRadius: 0.05,
    height: 1,
    width: 1,
    backgroundColor: '#F00',
    justifyContent: 'center',
  },
  triggerText: {
    alignSelf: 'center',
    fontSize: 0.2,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  menu:{
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingLeft: 0.03,
    paddingRight: 0.03,
    transform: [{translateZ: -1.25}],
    position: 'absolute',
    bottom: -0.7,
    right: -0.375,
    flexDirection: 'row',
  },
  menuText:{
    fontSize: 0.04,
    margin: 0.01,
    padding: 0.005,
    justifyContent: 'center',
  },
  menuButton:{
    margin: 0.01,
    backgroundColor: '#2fa504',
    justifyContent: 'center',
  },
  tooltipList:{
    padding: 0.02,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    transform: [{translateZ: -1.5}],
    position: 'absolute',
    flexDirection: 'column',
    bottom: -.7,
    right: -0.45,
  },
  tooltipListItem:{
    backgroundColor: '#224b8e',
    fontSize: 0.04,
    margin: 0.01,
    padding: 0.005,
  },
  tooltipListItemSelected:{
    backgroundColor: '#4286f4',
    fontSize: 0.04,
    margin: 0.01,
    padding: 0.005,
  },
  tooltipListRow:{
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  tooltipListImage:{
    width: 0.06,
    height: 0.06,
    margin: 0.01,
    padding: 0.005,
  },
  // positionButtons:{
  // },
  // pBButton:{
  //   backgroundColor: 'rgba(50, 0, 100, 0.3)',
  // },
  pBLeft:{
    backgroundColor: '#2fa504',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.7,
    right: -0.65,
    width: 0.13,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBRight:{
    backgroundColor: '#2fa504',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.7,
    right: -.95,
    width: 0.13,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBUp:{
    backgroundColor: '#2fa504',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.625,
    right: -0.8,
    width: 0.13,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBDown:{
    backgroundColor: '#2fa504',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.7,
    right: -0.8,
    width: 0.13,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBPlus:{
    backgroundColor: '#25baa3',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.778,
    right: -0.7,
    width: 0.05,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBRate:{
    backgroundColor: 'rgba(50, 0, 100, 0.7)',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.778,
    right: -0.775,
    width: 0.075,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBMinus:{
    backgroundColor: '#25baa3',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -.778,
    right: -0.825,
    width: 0.05,
    height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  pBRateBar:{
    // backgroundColor: 'rgba(50, 0, 100, 0.3)',
    position: 'absolute',
    transform: [{translateZ: -1.5}],
    bottom: -0.85,
    right: -0.885,
    width: 0.3,
    height: 0.05,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  pBRateBarButton:{
    backgroundColor: 'rgba(50, 0, 100, 0.3)',
    height: 0.04,
     padding: 0.002,
     justifyContent: 'center',
  },
  pBRateBarButtonSelected:{
    backgroundColor: 'rgba(50, 0, 100, 0.7)',
    height: 0.04,
     padding: 0.002,
     justifyContent: 'center',
  },
  barText:{
    fontSize: 0.02,
    margin: 0.01,
    padding: 0.002,
    justifyContent: 'center',
  },
  selection:{
    backgroundColor: 'rgba(50, 50, 50, 0.7)',
    position: 'absolute',
    transform: [{translateZ: -1.25}],
    top: -0.72,
    right: 0,
    // width: 0.13,
    // height: 0.06,
    justifyContent: 'center',
    // padding: 0.005,
  },
  selectionImage:{
    width: 0.06,
    height: 0.06,
    margin: 0.005,
    padding: 0.0025,
  },
});
